---

- hosts: webservers
  become: true
  tasks:

  - name: copy html file
    copy:
      src: ~/ansible/tutorial_files_dir/tutorial.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
