---

- hosts: all
  become: true
  tasks:

  - name: install apache2 and php packages, also update cache, only when OS is Ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
